name: Build and Release Executable

on:
  push:
    tags:
      - 'v*' # Triggers whenever you push a tag like v1.0.0, v1.0.1

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter watchdog requests

    - name: Compile Executable
      run: |
        pyinstaller --noconsole --onefile --name="SmartFileOrganizer" index.py

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/SmartFileOrganizer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}